### ISSUE TITLE
Añadir la "hardware.md" a la carpeta unidad 1

### ISSUE THREAD

**Issue by bananas24** [damichers/apuntes-si#17]
Crea la carpeta `unit1` y añade un fichero llamado `hardware.md` con los siguientes contenidos:

-Hardware de un sistema informático
--Carcasa o caja del ordenador
--Fuente de alimentación
--Placa base o motherboard
--Memoria
--CPU o Microprocesador

**Comment by James-mac-y** [comment]
ok boss

**Comment by James-mac-y** [comment]
fin de la issue
